
spring:
    datasource:
        url: jdbcpostgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
        username: rdcodigo
        password: 0245
    jpa: 
        show-sql: true
        hibernate:
            ddl-auto: update